

DROP TABLE TAB_STRSJOBAUDIT
GO

CREATE TABLE TAB_STRSJOBAUDIT
(	STRSJOBID INT NOT NULL, 
	STRSINPUTCHANNEL VARCHAR(20), 
	STRSINPUTFILE VARCHAR(80), 
	STRSSAVEFILE VARCHAR(150), 
	STRSPROJECTNAME VARCHAR(40), 
	STRSJOBBEGIN DATETIME2,
	STRSJOBEND DATETIME2, 
	STRSJOBSTATUS VARCHAR(50), 
	STRSNODENAME VARCHAR(50), 
	STRSNODEIP VARCHAR(50),
	CONSTRAINT  PK_TAB_STRSJOBAUDIT_STRSJOBID 
		UNIQUE clustered(STRSJOBID, STRSPROJECTNAME)
) 

GRANT SELECT ON TAB_STRSJOBAUDIT TO StrsSolutionDB
GO