

DROP INDEX	IX_TAB_STRSAFP_STRSSSORTFILEID ON TAB_STRSAFP,
			IX_TAB_STRSAFP_STRSBATCHID ON TAB_STRSAFP,
			IX_TAB_STRSAFP_STRSJOBID ON TAB_STRSAFP
GO

DROP TABLE TAB_STRSAFP
GO

CREATE TABLE TAB_STRSAFP 
(	STRSAFPID VARCHAR(100) NOT NULL, 
	AFPFILENAME VARCHAR(80),
	SORTCODE VARCHAR(10),
	PLEX VARCHAR(10),	  
	COMPLETEDATETIME DATETIME2,   
	TOTALDOCPROCESSED INT, 
	AFPFILEPATH VARCHAR(150),
	BATCHDATE VARCHAR(8),
	STRSSSORTFILEID VARCHAR(30),
	STRSBATCHID VARCHAR(20), 
	STRSJOBID INT NOT NULL,
	BEGINPSTRAYID INT,
	ENDPSTRAYID INT,
	BEGINPSSEQUENCE INT,
	ENDPSSEQUENCE INT,
		CONSTRAINT PK_TAB_STRSAFP_STRSAFPID
		PRIMARY KEY CLUSTERED (STRSAFPID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSAFP_STRSSSORTFILEID
	ON TAB_STRSAFP (STRSSSORTFILEID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSAFP_STRSBATCHID
	ON TAB_STRSAFP (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSAFP_STRSJOBID
	ON TAB_STRSAFP (STRSJOBID ASC)
GO

GRANT SELECT ON TAB_STRSAFP TO StrsSolutionDB
GO