--- This is the timing from dirscan to db+ doc
SELECT DATEDIFF(ss, ja.STRSJOBBEGIN, ja.STRSJOBEND) AS TimeSecs, s.*, ja.*
FROM TAB_STRSSPOOL s INNER JOIN TAB_STRSJOBAUDIT ja ON ja.STRSJOBID = s.STRSSPOOOLJOBID
WHERE 1 = 1

--Time from trailer received to batch complete
SELECT DATEDIFF(ss, TRAILERRECEIVED, BATCH_COMPLETE) AS TimeSecs FROM VW_BATCH_DETAIL

--Time from PCO init to PCO files created
SELECT * FROM TAB_STRSPRESORTFILE
--USE THE VW_BATCH_DETAIL TO GET THE BATCH COMPLETE DATE TO GET TIME WHEN BATCH IS RECONCILED 


--From PCO to Begin AFP
-- JOIN STRSPRESORTFILE WITH VW_BATCH_DETAIL TO GET THE TIMING PER SPOOL (cOMMERCIAL, RESIDENTIAL, etc) OTHER SORT CODES, OUTSORTS.
--USE THE sENTDATETIME AND RETURNEDdATETIME  


-- AFP processing duration
select datediff(minute, STRSJOBBEGIN, STRSJOBEND) DURATION, * from TAB_STRSJOBAUDIT where STRSINPUTCHANNEL ='in_ppq_afp'

-- PDF processing duration
select datediff(minute, STRSJOBBEGIN, STRSJOBEND) DURATION, * from TAB_STRSJOBAUDIT where STRSINPUTCHANNEL ='in_ppq_pdf'

--When all else fails
select * from TAB_STRSJOBAUDIT
--use appropriate filter
