
DROP VIEW VW_MECHANICAL_MAIL_REPORT
GO

CREATE VIEW VW_MECHANICAL_MAIL_REPORT
AS 
	SELECT 
		A.STRSAFPID,
		MAX(A.SORTCODE) SORTCODE,
		MAX(A.AFPFILENAME) AFPFILENAME,
		MAX(A.TOTALDOCPROCESSED) TOTALDOCPROCESSED,
		COUNT(I.STRSDOCID) NUM_OF_BILLS,
		(SELECT COUNT(E.STRSENVELOPEID) FROM VW_ENVELOPE_DETAIL E WHERE E.STRSSSORTFILEID = MAX(A.STRSSSORTFILEID)) NUM_OF_MAILPIECES,
		SUM(P.PAGECOUNT) PAGECOUNT,
		MAX(I.BATCHDATE) BATCHDATE
	FROM 
		TAB_STRSAFP AS A
			JOIN
		TAB_STRSINV AS I
			ON I.STRSAFPID = A.STRSAFPID
			JOIN
		TAB_STRSPOSTALADRS AS P
			ON P.STRSDOCID = I.STRSDOCID
	GROUP BY
		A.STRSAFPID
GO

GRANT SELECT ON VW_MECHANICAL_MAIL_REPORT TO StrsSolutionDB 
GO