

DROP VIEW VW_BATCH_DETAIL
GO

CREATE VIEW VW_BATCH_DETAIL
AS 
	SELECT 
		b.STRSBATCHID,
		MAX(b.BATCHDATE) BATCHDATE,
		MAX(b.BATCHTYPE) BATCHTYPE,
		MAX(b.BATCHCYCLE) BATCHCYCLE,
		MIN(s.CREATEDATETIME) BATCH_START,
		COUNT(s.STRSSPOOLID) SPOOLCOUNT,
		MAX(b.SPOOLCOUNT) TRAILER_SPOOLCOUNT,
		(select count(*) from TAB_STRSINV where STRSBATCHID = b.STRSBATCHID) INV_TOTALDOCPROCESSED,
		(select count(*) from TAB_STRSCORR where STRSBATCHID = b.STRSBATCHID) CORR_TOTALDOCPROCESSED,
		(select count(*) from TAB_STRSCOCM where STRSBATCHID = b.STRSBATCHID) COCM_TOTALDOCPROCESSED,
		(select count(*) from TAB_STRSEBILL where STRSBATCHID = b.STRSBATCHID) EBILL_TOTALDOCPROCESSED,
		(select count(*) from TAB_STRSINV where STRSBATCHID = b.STRSBATCHID and EDIFLAG = 'X') EDI_TOTALDOCPROCESSED,
		MAX(b.TOTALDOCSSENT) TRAILER_TOTALDOCSENT,
		SUM(s.TOTALDOCSENT) SPOOL_TOTALDOCSENT,
		SUM(s.TOTALDOCPROCESSED) SPOOL_TOTALDOCPROCESSED,
		MAX(j.STRSJOBBEGIN) TRAILERRECEIVED,
		MIN(j.STRSINPUTFILE) TRAILERFILENAME,
		MAX(b.DATETIMECOMPLETE) BATCH_COMPLETE,
		DATEDIFF(mi, MIN(s.CREATEDATETIME), MAX(b.DATETIMECOMPLETE)) BATCH_DURATION_MM
	FROM 
		dbo.TAB_STRSBATCH AS b
			JOIN
		dbo.TAB_STRSSPOOL AS s
			ON b.STRSBATCHID = s.STRSBATCHID
			JOIN
		dbo.TAB_STRSJOBAUDIT AS j
			ON b.STRSJOBID = j.STRSJOBID
	GROUP BY
		b.STRSBATCHID
GO

GRANT SELECT ON VW_BATCH_DETAIL TO StrsSolutionDB
GO