
DROP VIEW VW_EBILL_EMAIL
GO

CREATE VIEW VW_EBILL_EMAIL
AS 
	SELECT 
		b.STRSBATCHID, 
		b.BATCHDATE,
		e.BILLTYPE,
		e.SEGMENT,
		e.STRSDOCID,
		e.EMAILADDRESS,
		e.HTMLFILE,
		e.IMAGEFILE
	FROM dbo.TAB_STRSEBILL AS e
		JOIN dbo.TAB_STRSBATCH AS b ON e.STRSBATCHID = b.STRSBATCHID
GO

GRANT SELECT ON VW_EBILL_EMAIL TO StrsSolutionDB
GO