

DROP VIEW VW_INV_MAIL_REPORT
GO

CREATE VIEW VW_INV_MAIL_REPORT
AS 
	SELECT 
		MMR.STRSAFPID,
		MAX(MMR.SORTCODE) SORTCODE, 
		COUNT(MMR.I_STRSDOCID) + COUNT(DISTINCT(MMR.C_STRSDOCID)) DOC_TABLE_COUNT,
		COUNT(DISTINCT(MMR.STRSENVELOPEID)) ENV_COUNT_DOCTYPE,
		SUM(MMR.PAGECOUNT) PAGECOUNT,
		SUM(MMR.SHEETCOUNT) SHEETCOUNT,
		MAX(MMR.AFPFILENAME) AFPFILENAME,
		MAX(MMR.TOTALDOCPROCESSED) AFP_TOTALDOCPROCESSED,
		(COUNT(MMR.I_STRSDOCID) + COUNT(DISTINCT(MMR.C_STRSDOCID)) ) - MAX(MMR.TOTALDOCPROCESSED) DOC_TABLE_AFP_DIFF,
		MAX(MMR.BEGINPSTRAYID) BEGINPSTRAYID,
		MAX(MMR.ENDPSTRAYID) ENDPSTRAYID,
		MAX(MMR.BEGINPSSEQUENCE) BEGINPSSEQUENCE,
		MAX(MMR.ENDPSSEQUENCE) ENDPSSEQUENCE,
		MAX(MMR.BATCHDATE) BATCHDATE,
		COUNT(CASE WHEN MMR.OTTFLAG = 'X' THEN 1 ElSE NULL END) OTT_COUNT
	FROM (	SELECT 
				I.STRSDOCID I_STRSDOCID,
				C.STRSDOCID C_STRSDOCID,
				P.SORTCODE SORTCODE,
				P.COPIES COPIES,
				P.PAGECOUNT PAGECOUNT,
				P.SHEETCOUNT SHEETCOUNT,
				P.WEIGHT WEIGHT,
				A.AFPFILENAME AFPFILENAME,
				A.TOTALDOCPROCESSED TOTALDOCPROCESSED,
				A.BEGINPSTRAYID BEGINPSTRAYID,
				A.ENDPSTRAYID ENDPSTRAYID,
				A.BEGINPSSEQUENCE BEGINPSSEQUENCE,
				A.ENDPSSEQUENCE ENDPSSEQUENCE,
				I.BATCHDATE BATCHDATE,
				I.STRSBATCHID STRSBATCHID,
				I.STRSSPOOLID STRSSPOOLID,
				P.STRSENVELOPEID STRSENVELOPEID,
				I.STRSAFPID	STRSAFPID,
				I.OTTFLAG OTTFLAG	
			FROM dbo.TAB_STRSINV AS I
				JOIN
			dbo.TAB_STRSPOSTALADRS AS P ON P.STRSDOCID = I.STRSDOCID
				JOIN
			dbo.TAB_STRSAFP AS A ON A.STRSAFPID = I.STRSAFPID
				LEFT JOIN
			dbo.TAB_STRSCORR AS C ON C.STRSAFPID = I.STRSAFPID
	) AS MMR
	GROUP BY MMR.STRSAFPID
GO

GRANT SELECT ON VW_INV_MAIL_REPORT TO StrsSolutionDB 
GO