
DROP VIEW VW_NOTIFICATION_DETAIL
GO

CREATE VIEW VW_NOTIFICATION_DETAIL
AS 
	SELECT 
		 N.STRNOTIFICATIONID,
		 N.CREATEDATETIME,
		 N.NOTIFICATIONTYPE,
		 N.NOTIFICATIONCLASS,
		 N.BATCHDATE,
		 N.PROJECTNAME,
		 N.FUNCTIONCLASS,
		 N.FUNCTIONCNAME,
		 N.NOTIFICATION,
		 JA.STRSINPUTFILE,
		 JA.STRSINPUTCHANNEL,
		 JA.STRSNODEIP,
		 JA.STRSJOBSTATUS,
		 N.STRSJOBID,
		 JA.STRSSAVEFILE
	FROM dbo.TAB_STRSNOTIFICATIONS N 
		INNER JOIN dbo.TAB_STRSJOBAUDIT JA ON N.STRSJOBID = JA.STRSJOBID
GO

GRANT SELECT ON VW_NOTIFICATION_DETAIL TO StrsSolutionDB
GO