

DROP INDEX	IX_TAB_STRSBATCH_STRSJOBID ON TAB_STRSBATCH
GO

DROP TABLE TAB_STRSBATCH
GO

CREATE TABLE TAB_STRSBATCH 
(	STRSBATCHID VARCHAR(20) NOT NULL, 
	BATCHTYPE VARCHAR(30),
	BATCHDATE VARCHAR(8),
	BATCHCYCLE VARCHAR(5),
	SPOOLCOUNT INT,
	TOTALDOCSSENT INT, 
	DATETIMERECEIVED DATETIME2, 
	DATETIMECOMPLETE DATETIME2,  
	STRSJOBID INT NOT NULL,
		CONSTRAINT PK_TAB_STRSBATCH_STRSBATCHID
		PRIMARY KEY CLUSTERED (STRSBATCHID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSBATCH_STRSJOBID
	ON TAB_STRSBATCH (STRSJOBID ASC)
GO

GRANT SELECT ON TAB_STRSBATCH TO StrsSolutionDB
GO