

DROP INDEX	IX_TAB_STRSSPOOL_STRSBATCHID ON TAB_STRSSPOOL,
			IX_TAB_STRSSPOOL_STRSTRAILERJOBID ON TAB_STRSSPOOL,
			IX_TAB_STRSSPOOL_STRSSPOOOLJOBID ON TAB_STRSSPOOL
GO

DROP TABLE TAB_STRSSPOOL
GO

CREATE TABLE TAB_STRSSPOOL 
(	STRSSPOOLID VARCHAR(20) NOT NULL,
	SPOOLTYPE VARCHAR(20),  
	CREATEDATETIME DATETIME2,   
	COMPLETEDATETIME DATETIME2,   
	TOTALDOCPROCESSED INT, 
	TRAILERRECEIVED DATETIME2,
	TOTALDOCSENT INT,
	SPOOLTITLE VARCHAR(50),
	STRSBATCHID VARCHAR(20), 
	STRSBATCHDATE VARCHAR(15),
	STRSTRAILERJOBID INT,
	STRSSPOOOLJOBID INT NOT NULL
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSSPOOL_STRSBATCHID
	ON TAB_STRSSPOOL (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSSPOOL_STRSTRAILERJOBID
	ON TAB_STRSSPOOL (STRSTRAILERJOBID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSSPOOL_STRSSPOOOLJOBID
	ON TAB_STRSSPOOL (STRSSPOOOLJOBID ASC)
GO

GRANT SELECT ON TAB_STRSSPOOL TO StrsSolutionDB
GO