

DROP INDEX	IX_TAB_STRSPOSTPROCESSOR_STRSBATCHID ON TAB_STRSPOSTPROCESSOR,
			IX_TAB_STRSPOSTPROCESSOR_STRSJOBID ON TAB_STRSPOSTPROCESSOR
GO

DROP TABLE TAB_STRSPOSTPROCESSOR
GO

CREATE TABLE TAB_STRSPOSTPROCESSOR 
(	STRSPPID VARCHAR(20) NOT NULL,
	PPQTYPE VARCHAR(20), 
	PPQFILENAME VARCHAR(80),	
	CREATEDATETIME DATETIME2,   
	COMPLETEDATETIME DATETIME2,   
	TOTALDOCPROCESSED INT, 
	STRSBATCHID VARCHAR(20), 
	STRSJOBID INT NOT NULL,
		CONSTRAINT PK_TAB_STRSPOSTPROCESSOR_STRSPPID
		PRIMARY KEY CLUSTERED (STRSPPID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTPROCESSOR_STRSBATCHID
	ON TAB_STRSPOSTPROCESSOR (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTPROCESSOR_STRSJOBID
	ON TAB_STRSPOSTPROCESSOR (STRSJOBID ASC)

GRANT SELECT ON TAB_STRSPOSTPROCESSOR TO StrsSolutionDB
GO