

DROP INDEX	IX_TAB_STRSINSERTS_STRSDOCID ON TAB_STRSINSERTS,
			IX_TAB_STRSINSERTS_BINNUMBER ON TAB_STRSINSERTS
GO

DROP TABLE TAB_STRSINSERTS
GO

CREATE TABLE TAB_STRSINSERTS
(	STRSINSERTID VARCHAR(80) NOT NULL, 
	CREATEDATETIME DATETIME2,
	INSERTDESCRIPTION VARCHAR(80),
	INSERTWEIGHT DECIMAL(5,2),
	BINNUMBER INT,	
	STRSDOCID VARCHAR(50) NOT NULL,  
		CONSTRAINT PK_TAB_STRSINSERTS_STRSINSERTID
		PRIMARY KEY CLUSTERED (STRSINSERTID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSINSERTS_STRSDOCID
	ON TAB_STRSINSERTS (STRSDOCID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSINSERTS_BINNUMBER
	ON TAB_STRSINSERTS (BINNUMBER ASC)
GO

GRANT SELECT ON TAB_STRSINSERTS TO StrsSolutionDB
GO