

DROP INDEX	IX_TAB_STRSPOSTALOPT_STRSSSORTFILEID ON TAB_STRSPOSTALOPT,
			IX_TAB_STRSPOSTALOPT_STRSJOBID ON TAB_STRSPOSTALOPT,
			IX_TAB_STRSPOSTALOPT_STRSBATCHDATE ON TAB_STRSPOSTALOPT,
			IX_TAB_STRSPOSTALOPT_STRSENVELOPEID ON TAB_STRSPOSTALOPT
GO

DROP TABLE TAB_STRSPOSTALOPT
GO

CREATE TABLE TAB_STRSPOSTALOPT 
(	STRSENVELOPEID VARCHAR(50) NOT NULL,  
	MAILTYPE VARCHAR(10),
	DSCUSTOMERNAME VARCHAR(50),
	DSATT VARCHAR(50),
	DSSECDADDR VARCHAR(50),
	DSADDRESSLINE1 VARCHAR(50),
	DSADDRESSLINE2 VARCHAR(50),
	DSZIP INT,
	DSZIPEXT VARCHAR(10),
	DSCITY VARCHAR(40),
	DSSTATE VARCHAR(5),
	DSCOUNTRY VARCHAR(20),	
	DSDPVSTATUS INT,
	DSROUTECODE VARCHAR(5),
	DSMEMOIDN INT,
	DSNCOAFLAG char(1),
	PSZIPMARK char(1),
	PSENDORSELINE VARCHAR(100),
	PSOUTPUTCLASS VARCHAR(50),
	PSIMBBARCODE VARCHAR(50),
	PSTRAYID INT,
	PSPALLETID INT,
	PSSEQUENCE INT,
	PSTRAYSIZE INT,
	STRSSSORTFILEID VARCHAR(30),
 	STRSJOBID INT,
	STRSMULTICOUPONFLAG CHAR(1),
	STRSBATCHDATE VARCHAR(10)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALOPT_STRSSSORTFILEID
	ON TAB_STRSPOSTALOPT (STRSSSORTFILEID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALOPT_STRSENVELOPEID
	ON TAB_STRSPOSTALOPT (STRSENVELOPEID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALOPT_STRSJOBID
	ON TAB_STRSPOSTALOPT (STRSJOBID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALOPT_STRSBATCHDATE
	ON TAB_STRSPOSTALOPT (STRSBATCHDATE ASC)
GO

GRANT SELECT ON TAB_STRSPOSTALOPT TO StrsSolutionDB
GO