

DROP INDEX	IX_TAB_STRSPRESORTFILE_STRSBATCHID ON TAB_STRSPRESORTFILE,
			IX_TAB_STRSPRESORTFILE_STRSJOBID ON TAB_STRSPRESORTFILE
GO

DROP TABLE TAB_STRSPRESORTFILE
GO

CREATE TABLE TAB_STRSPRESORTFILE 
(	STRSSSORTFILEID VARCHAR(30) NOT NULL, 
	SORTCODE VARCHAR(10),
	FILENAME VARCHAR(80), 
	RECORDCOUNTSENT INT, 
	RECORDCOUNTRETURNED INT, 
	SENTDATETIME DATETIME2,
	RETURNEDDATETIME DATETIME2,
	DOCUPDENDDATETIME DATETIME2,
	PROCESSCOMPLETE INT, 
	STRSBATCHID VARCHAR(20) NOT NULL,
	STRSJOBID INT NOT NULL,
	CONSTRAINT PK_TAB_STRSPRESORTFILE_STRSSSORTFILEID
		PRIMARY KEY CLUSTERED (STRSSSORTFILEID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPRESORTFILE_STRSBATCHID
	ON TAB_STRSPRESORTFILE (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPRESORTFILE_STRSJOBID
	ON TAB_STRSPRESORTFILE (STRSJOBID ASC)

GRANT SELECT ON TAB_STRSPRESORTFILE TO StrsSolutionDB
GO