

DROP INDEX	IX_TAB_STRSNOTIFICATIONS_STRSJOBID ON TAB_STRSNOTIFICATIONS
GO

DROP TABLE TAB_STRSNOTIFICATIONS
GO

CREATE TABLE TAB_STRSNOTIFICATIONS
(	STRNOTIFICATIONID VARCHAR(20) NOT NULL,
	CREATEDATETIME DATETIME2,
	NOTIFICATIONTYPE VARCHAR(20), 
	NOTIFICATIONCLASS VARCHAR(10), 
	STRSJOBID INT NOT NULL, 
	BATCHDATE VARCHAR(8),
	PROJECTNAME VARCHAR(40), 
	FUNCTIONCLASS VARCHAR(5), 
	FUNCTIONCNAME VARCHAR(50),
	NOTIFICATION VARCHAR(1000))

GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSNOTIFICATIONS_STRSJOBID
	ON TAB_STRSNOTIFICATIONS (STRSJOBID ASC)
GO

GRANT SELECT ON TAB_STRSNOTIFICATIONS TO StrsSolutionDB
GO