/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [STRSJOBID],[STRSINPUTCHANNEL],[STRSFILENAME],[STRSPROJECTNAME],[STRSJOBBEGIN],[STRSJOBEND],[STRSJOBSTATUS],[STRSNODENAME],[STRSNODEIP]
  FROM [StrsSolutionDB].[dbo].[TAB_STRSJOBAUDIT];

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [STRSDOCID],[CREATEDATETIME],[CHANNEL],[RESEND],[ACCOUNTNUMBER],[CUSTOMERNAME],[DOCUMENTDATE],[BILLDUEDATE],[BILLTYPE],[TOTALAMOUNTDUE],[BILLFROMDATE],[BILLTODATE],[PRINTCOMPLETE],[ARCHIVECOMPLETE],[STRSJOBID]
  FROM [StrsSolutionDB].[dbo].[TAB_STRSINV];

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [STRSSSORTFILEID],[CREATEDATETIME],[FILENAME],[RECORDCOUNTSENT],[RECORDCOUNTRETURNED],[SENTDATETIME],[RETURNEDDATETIME],[DOCUPDENDDATETIME],[PROCESSCOMPLETE],[ERRORMESSAGE],[STRSJOBID]
  FROM [StrsSolutionDB].[dbo].[TAB_STRSPRESORTFILE];

  /****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [STRSADRSID],[MAILTYPE],[DPCUSOTMERNAME],[DPADDRLINE1],[DPADDRLINE2],[DPADDRLINE3],[DPZIP],[DPZIPEXT],[DPCITY],[DPSTATE],[DPCOUNTRY],[FOREIGNADDRESS],[COPIES],[PAGECOUNT],[WEIGHT],[ZIPMARK],[IMB],[SCANLINE],[TWODBARCODEDATA],[TWODBARCODEDATAREMIT],[TRAYTAGNUMBER],[STRSDOCID],[STRSSSORTFILEID]
  FROM [StrsSolutionDB].[dbo].[TAB_STRSPOSTALADRS];