select * from TAB_STRSJOBAUDIT
where STRSJOBSTATUS = 'in progress'
order by STRSJOBBEGIN

select count(*) TAB_STRSINV from TAB_STRSINV where BATCHDATE in ('20170407')
select count(*) TAB_STRSCORR from TAB_STRSCORR where BATCHDATE  in ('20170407')
select count(*) TAB_STRSCOCM from TAB_STRSCOCM c join TAB_STRSBATCH b on b.STRSBATCHID = c.STRSBATCHID where b.BATCHDATE in ('20170407')
select count(*) TAB_STRSEBILL from TAB_STRSEBILL e join TAB_STRSBATCH b on b.STRSBATCHID = e.STRSBATCHID where b.BATCHDATE in ('20170407')

select * from TAB_STRSSPOOL where STRSBATCHDATE in ('20170407')
select * from TAB_STRSBATCH where BATCHDATE in ('20170407') order by STRSBATCHID asc
select STRSBATCHID,  COUNT(STRSBATCHID), SUM(TOTALDOCPROCESSED), SUM(TOTALDOCSENT) from TAB_STRSSPOOL where STRSBATCHDATE in ('20170407')  group by STRSBATCHID order by STRSBATCHID asc

select * from TAB_STRSPRESORTFILE order by SENTDATETIME desc

select * from TAB_STRSAFP where BATCHDATE in ('20170407')

select * from VW_INV_MAIL_REPORT where BATCHDATE in ('20170407')
select * from VW_CORR_MAIL_REPORT where BATCHDATE in ('20170407')