
DROP VIEW VW_ENVELOPE_DETAIL
GO

CREATE VIEW VW_ENVELOPE_DETAIL
AS 
/*
	SELECT 
		PA.STRSENVELOPEID STRSENVELOPEID,
		MAX(PA.DPCUSTOMERNAME) DPCUSTOMERNAME,
		MAX(PA.DPADDRLINE1) DPADDRLINE1,
		MAX(PA.DPADDRLINE2) DPADDRLINE2,
		MAX(PA.DPADDRLINE3) DPADDRLINE3,
		MAX(PA.DPZIP) DPZIP,
		MAX(PA.DPZIPEXT) DPZIPEXT,
		MAX(PA.DPCITY) DPCITY,
		MAX(PA.DPSTATE) DPSTATE,
		MAX(PA.DPCOUNTRY) DPCOUNTRY,
		SUM(PA.COPIES) COPIES,
		SUM(PA.PAGECOUNT) PAGECOUNT,
		SUM(PA.SHEETCOUNT) SHEETCOUNT,
		SUM(PA.WEIGHT) DOC_WEIGHT,
		I.INSERTDESCRIPTION INSERTDESCRIPTION,
		SUM(I.INSERTWEIGHT) INSERTWEIGHT,
		SUM(PA.WEIGHT) + SUM(I.INSERTWEIGHT) ENVELOPEWEIGHT,
		MAX(CASE WHEN I.BINNUMBER = 1 THEN 'X' ELSE '' END) BIN_1,
		MAX(CASE WHEN I.BINNUMBER = 2 THEN 'X' ELSE '' END) BIN_2,
		MAX(CASE WHEN I.BINNUMBER = 3 THEN 'X' ELSE '' END) BIN_3,
		MAX(CASE WHEN I.BINNUMBER = 4 THEN 'X' ELSE '' END) BIN_4,
		MAX(CASE WHEN I.BINNUMBER = 5 THEN 'X' ELSE '' END) BIN_5,
		MAX(CASE WHEN I.BINNUMBER = 6 THEN 'X' ELSE '' END) BIN_6,
		MAX(CASE WHEN I.BINNUMBER = 7 THEN 'X' ELSE '' END) BIN_7,
		MAX(CASE WHEN I.BINNUMBER = 8 THEN 'X' ELSE '' END) BIN_8
	FROM TAB_STRSPOSTALADRS PA
	INNER JOIN TAB_STRSINSERTS I ON PA.STRSDOCID = I.STRSDOCID
	GROUP BY PA.STRSENVELOPEID, I.INSERTDESCRIPTION
	*/
	SELECT 
		CONCAT(row_number() OVER (ORDER BY PA.STRSCONCATADDRESS), '_', MAX(PA.DPZIP)) STRSENVELOPEID,
		MAX(PA.DPCUSTOMERNAME) DPCUSTOMERNAME,
		MAX(PA.DPADDRLINE1) DPADDRLINE1,
		MAX(PA.DPADDRLINE2) DPADDRLINE2,
		MAX(PA.DPADDRLINE3) DPADDRLINE3,
		MAX(PA.DPZIP) DPZIP,
		MAX(PA.DPZIPEXT) DPZIPEXT,
		MAX(PA.DPCITY) DPCITY,
		MAX(PA.DPSTATE) DPSTATE,
		MAX(PA.DPCOUNTRY) DPCOUNTRY,
		PA.SORTCODE,
		PA.STRSCONCATADDRESS,
		SUM(PA.WEIGHT) + SUM(I.INSERTWEIGHT) ENVELOPEWEIGHT,
		(SELECT REPLACE(I.DOCUMENTTYPE, 'ZSS', '') FROM TAB_STRSINV I WHERE I.STRSDOCID = MAX(PA.STRSDOCID)) INV_DOCUMENTTYPE,
		(SELECT REPLACE(C.DOCUMENTTYPE, 'ZSS', '') FROM TAB_STRSCORR C WHERE C.STRSDOCID = MAX(PA.STRSDOCID)) CORR_DOCUMENTTYPE,
		(SELECT I.STRSBATCHID FROM TAB_STRSINV I WHERE I.STRSDOCID = MAX(PA.STRSDOCID)) INV_BATCHID,
		(SELECT C.STRSBATCHID FROM TAB_STRSCORR C WHERE C.STRSDOCID = MAX(PA.STRSDOCID)) CORR_BATCHID,
		MAX(PA.STRSSSORTFILEID) STRSSSORTFILEID
		-- ENVELOPEWEIGHT
	FROM TAB_STRSPOSTALADRS PA
	GROUP BY PA.STRSCONCATADDRESS, SORTCODE
GO

GRANT SELECT ON VW_ENVELOPE_DETAIL TO StrsSolutionDB
GO