USE [master]
GO
CREATE LOGIN [StrsSolutionDB] WITH PASSWORD=N'StreamServe123$' MUST_CHANGE, DEFAULT_DATABASE=[StrsSolutionDB], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [StrsSolutionDB]
GO
CREATE USER [StrsSolutionDB] FOR LOGIN [StrsSolutionDB]
GO