

DROP VIEW VW_INV_MAIL_REPORT
GO

CREATE VIEW VW_INV_MAIL_REPORT
AS 
	SELECT 
		MMR.STRSAFPID,
		MAX(MMR.SORTCODE) SORTCODE, 
		MMR.DOCUMENTTYPE,
		MAX(MMR.DOCUMENTTITLE) DOCUMENTTITLE,
		COUNT(MMR.STRSDOCID) DOC_COUNT,
		COUNT(DISTINCT(MMR.STRSENVELOPEID)) ENV_COUNT_DOCTYPE,
		SUM(MMR.PAGECOUNT) PAGECOUNT,
		SUM(MMR.SHEETCOUNT) SHEETCOUNT,
		MAX(MMR.AFPFILENAME) AFPFILENAME,
		MAX(MMR.TOTALDOCPROCESSED) AFP_TOTALDOCPROCESSED,
		MAX(MMR.BATCHDATE) BATCHDATE,
		COUNT(case when MMR.WEIGHT > 0.20 then 1 else 0 end) TOT_OVERWEIGHT_COUNT,
		COUNT(case when MMR.OTTFLAG = 'X' then 1 else 0 end) OTT_COUNT
	FROM (	SELECT 
				I.STRSDOCID STRSDOCID,
				I.DOCUMENTTYPE DOCUMENTTYPE,
				I.DOCUMENTTITLE DOCUMENTTITLE,
				P.SORTCODE SORTCODE,
				P.COPIES COPIES,
				P.PAGECOUNT PAGECOUNT,
				P.SHEETCOUNT SHEETCOUNT,
				P.WEIGHT WEIGHT,
				A.AFPFILENAME AFPFILENAME,
				A.TOTALDOCPROCESSED TOTALDOCPROCESSED,
				I.BATCHDATE BATCHDATE,
				I.STRSBATCHID STRSBATCHID,
				I.STRSSPOOLID STRSSPOOLID,
				P.STRSENVELOPEID STRSENVELOPEID,
				I.STRSAFPID	STRSAFPID,
				I.OTTFLAG OTTFLAG	
			FROM dbo.TAB_STRSINV AS I
				JOIN
			dbo.TAB_STRSPOSTALADRS AS P ON P.STRSDOCID = I.STRSDOCID
				JOIN
			dbo.TAB_STRSAFP AS A ON A.STRSAFPID = I.STRSAFPID
	) AS MMR
	GROUP BY MMR.STRSAFPID, MMR.DOCUMENTTYPE
		
GO

GRANT SELECT ON VW_INV_MAIL_REPORT TO StrsSolutionDB 
GO