
DROP VIEW VW_CORR_MAIL_REPORT
GO

CREATE VIEW VW_CORR_MAIL_REPORT
AS 
	SELECT 
		MMR.STRSAFPID,
		MAX(MMR.SORTCODE) SORTCODE, 
		MMR.DOCUMENTTYPE,
		MAX(MMR.DOCUMENTTITLE) DOCUMENTTITLE,
		COUNT(MMR.STRSDOCID) DOC_COUNT,
		COUNT(DISTINCT(MMR.STRSENVELOPEID)) ENV_COUNT_DOCTYPE,
		SUM(MMR.PAGECOUNT) PAGECOUNT,
		SUM(MMR.SHEETCOUNT) SHEETCOUNT,
		MAX(MMR.AFPFILENAME) AFPFILENAME,
		MAX(MMR.TOTALDOCPROCESSED) AFP_TOTALDOCPROCESSED,
		MAX(MMR.BATCHDATE) BATCHDATE
	FROM (	SELECT 
				C.STRSDOCID STRSDOCID,
				C.DOCUMENTTYPE DOCUMENTTYPE,
				C.DOCUMENTTITLE DOCUMENTTITLE,
				P.SORTCODE SORTCODE,
				P.COPIES COPIES,
				P.PAGECOUNT PAGECOUNT,
				P.SHEETCOUNT SHEETCOUNT,
				P.WEIGHT WEIGHT,
				A.AFPFILENAME AFPFILENAME,
				A.TOTALDOCPROCESSED TOTALDOCPROCESSED,
				C.BATCHDATE BATCHDATE,
				C.STRSBATCHID STRSBATCHID,
				C.STRSSPOOLID STRSSPOOLID,
				P.STRSENVELOPEID STRSENVELOPEID,
				C.STRSAFPID	STRSAFPID	
			FROM dbo.TAB_STRSCORR AS C
				JOIN
			dbo.TAB_STRSPOSTALADRS AS P ON P.STRSDOCID = C.STRSDOCID
				JOIN
			dbo.TAB_STRSAFP AS A ON A.STRSAFPID = C.STRSAFPID
	) AS MMR
	GROUP BY MMR.STRSAFPID, MMR.DOCUMENTTYPE
		
GO

GRANT SELECT ON VW_CORR_MAIL_REPORT TO StrsSolutionDB 
GO