

DROP INDEX	IX_TAB_STRSCORR_STRSAFPID ON TAB_STRSCORR,
			IX_TAB_STRSCORR_STRSSPOOLID ON TAB_STRSCORR,
			IX_TAB_STRSCORR_STRSBATCHID ON TAB_STRSCORR,
			IX_TAB_STRSCORR_STRSJOBID ON TAB_STRSCORR,
			IX_TAB_STRSCORR_CHANNEL ON TAB_STRSCORR,
			IX_TAB_STRSCORR_DOCUMENTTYPE ON TAB_STRSCORR
GO

DROP TABLE TAB_STRSCORR
GO

CREATE TABLE TAB_STRSCORR
(	STRSDOCID VARCHAR(50) NOT NULL, 
	CREATEDATETIME DATETIME2, 
	DOCUMENTTYPE VARCHAR(20),
	DOCUMENTTITLE VARCHAR(150),
	DOCUMENTCATEGORY VARCHAR(30),
	ACCOUNTNUMBER VARCHAR(15),
	CUSTOMERNAME VARCHAR(50), 
	DOCUMENTDATE VARCHAR(10), 
	CHANNEL VARCHAR(25), 
	RESEND CHAR(1),	
	REPRINT CHAR(1),	
	STRSAFPID VARCHAR(100),
	STRSPPIDARCHIVE VARCHAR(20),
	BATCHDATE VARCHAR(15),
	STRSSPOOLID VARCHAR(20) NOT NULL, 
	STRSBATCHID VARCHAR(20),
	STRSJOBID INT NOT NULL,
	CONSTRAINT PK_TAB_STRSCORR_STRSDOCID
		PRIMARY KEY CLUSTERED (STRSDOCID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCORR_STRSAFPID
	ON TAB_STRSCORR (STRSAFPID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCORR_STRSSPOOLID
	ON TAB_STRSCORR (STRSSPOOLID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCORR_STRSBATCHID
	ON TAB_STRSCORR (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCORR_STRSJOBID
	ON TAB_STRSCORR (STRSJOBID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCORR_CHANNEL
	ON TAB_STRSCORR (CHANNEL ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCORR_DOCUMENTTYPE
	ON TAB_STRSCORR (DOCUMENTTYPE ASC)
GO

GRANT SELECT ON TAB_STRSCORR TO StrsSolutionDB
GO