

DROP INDEX	IX_TAB_STRSCOCM_STRSSPOOLID ON TAB_STRSCOCM,
			IX_TAB_STRSCOCM_STRSBATCHID ON TAB_STRSCOCM,
			IX_TAB_STRSCOCM_STRSJOBID ON TAB_STRSCOCM
GO

DROP TABLE TAB_STRSCOCM
GO

CREATE TABLE TAB_STRSCOCM
(	STRSDOCID VARCHAR(50) NOT NULL, 
	CREATEDATETIME DATETIME2, 
	DOCUMENTTYPE VARCHAR(20),
	DOCUMENTCATEGORY VARCHAR(30),
	ACCOUNTNUMBER VARCHAR(15),
	CUSTOMERNAME VARCHAR(50), 
	CUSTOMEREMAIL VARCHAR(200),
	PREMADDRESS VARCHAR(500),
	COCMDATE VARCHAR(10), 
	GUID VARCHAR(40),
	COKEY VARCHAR(40),
	CHANNEL VARCHAR(25), 	
	HTTPRESPONSE VARCHAR(200),
	ARCHIVECOMPLETE CHAR(1),
	STRSSPOOLID VARCHAR(20) NOT NULL, 
	STRSBATCHID VARCHAR(20) NOT NULL,
	STRSJOBID INT NOT NULL,
	CONSTRAINT PK_TAB_STRSCOCM_STRSDOCID
		PRIMARY KEY CLUSTERED (STRSDOCID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCOCM_STRSSPOOLID
	ON TAB_STRSCOCM (STRSSPOOLID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCOCM_STRSBATCHID
	ON TAB_STRSCOCM (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCOCM_STRSJOBID
	ON TAB_STRSCOCM (STRSJOBID ASC)
GO

GRANT SELECT ON TAB_STRSCOCM TO StrsSolutionDB
GO