

DROP INDEX	IX_TAB_STRSPOSTALADRS_STRSDOCID ON TAB_STRSPOSTALADRS,
			IX_TAB_STRSPOSTALADRS_STRSCONCATADDRESS ON TAB_STRSPOSTALADRS,
			IX_TAB_STRSPOSTALADRS_SORTCODE ON TAB_STRSPOSTALADRS,
			IX_TAB_STRSPOSTALADRS_STRSENVELOPEID ON TAB_STRSPOSTALADRS,
			IX_TAB_STRSPOSTALADRS_STRSBATCHDATE ON TAB_STRSPOSTALADRS,
			IX_TAB_STRSPOSTALADRS_BPNUMBER ON TAB_STRSPOSTALADRS,
			IX_TAB_STRSPOSTALADRS_STRSSSORTFILEID ON TAB_STRSPOSTALADRS
GO

DROP TABLE TAB_STRSPOSTALADRS
GO

CREATE TABLE TAB_STRSPOSTALADRS 
(	STRSADRSID VARCHAR(20) NOT NULL,  
	MAILTYPE VARCHAR(10), 
	SORTCODE VARCHAR(10),
	DPCUSTOMERNAME VARCHAR(50), 	
	DPATT VARCHAR(50), 
	DPSECDADDR VARCHAR(50),
	DPADDRLINE1 VARCHAR(50), 
	DPADDRLINE2 VARCHAR(50), 
	DPZIP VARCHAR(5),
	DPZIPEXT VARCHAR(10),
	DPCITY VARCHAR(40),
	DPSTATE VARCHAR(5), 
	DPCOUNTRY VARCHAR(20),
	FOREIGNADDRESS CHAR(1),
	COPIES INT,	
	PAGECOUNT INT,
	SHEETCOUNT INT,
	WEIGHT DECIMAL(5,2),
	SCANLINE VARCHAR(60),
	STRSDOCID VARCHAR(50) NOT NULL,
	STRSCONCATADDRESS VARCHAR(500),
	STRSENVELOPEID VARCHAR(50),
	STRSSSORTFILEID VARCHAR(30),
	STRSMULTICOUPONFLAG CHAR(1),
	STRSBATCHDATE VARCHAR(15),
	BPNUMBER VARCHAR(12),
	CONSTRAINT PK_TAB_STRSPOSTALADRS_STRSADRSID 
		PRIMARY KEY CLUSTERED (STRSADRSID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_BPNUMBER 
	ON TAB_STRSPOSTALADRS (BPNUMBER ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_STRSBATCHDATE
	ON TAB_STRSPOSTALADRS (STRSBATCHDATE ASC)
GO
CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_STRSDOCID
	ON TAB_STRSPOSTALADRS (STRSDOCID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_STRSCONCATADDRESS
	ON TAB_STRSPOSTALADRS (STRSCONCATADDRESS ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_SORTCODE
	ON TAB_STRSPOSTALADRS (SORTCODE ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_STRSENVELOPEID
	ON TAB_STRSPOSTALADRS (STRSENVELOPEID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_STRSSSORTFILEID
	ON TAB_STRSPOSTALADRS (STRSSSORTFILEID ASC)
GO

GRANT SELECT ON TAB_STRSPOSTALADRS TO StrsSolutionDB
GO


