

DROP TABLE TAB_STRSJOBAUDIT
GO

CREATE TABLE TAB_STRSJOBAUDIT
(	STRSJOBID INT NOT NULL, 
	STRSINPUTCHANNEL VARCHAR(20), 
	STRSINPUTFILE VARCHAR(80), 
	STRSSAVEFILE VARCHAR(150), 
	STRSPROJECTNAME VARCHAR(40), 
	STRSJOBBEGIN DATETIME2,
	STRSJOBEND DATETIME2, 
	STRSJOBSTATUS VARCHAR(50), 
	STRSNODENAME VARCHAR(50), 
	STRSNODEIP VARCHAR(50),
	CONSTRAINT  PK_TAB_STRSJOBAUDIT_STRSJOBID 
		UNIQUE clustered(STRSJOBID, STRSPROJECTNAME)
) 

GRANT SELECT ON TAB_STRSJOBAUDIT TO StrsSolutionDB
GO

DROP INDEX	IX_TAB_STRSBATCH_STRSJOBID ON TAB_STRSBATCH
GO

DROP TABLE TAB_STRSBATCH
GO

CREATE TABLE TAB_STRSBATCH 
(	STRSBATCHID VARCHAR(20) NOT NULL, 
	BATCHTYPE VARCHAR(30),
	BATCHDATE VARCHAR(8),
	BATCHCYCLE VARCHAR(5),
	SPOOLCOUNT INT,
	TOTALDOCSSENT INT, 
	DATETIMERECEIVED DATETIME2, 
	DATETIMECOMPLETE DATETIME2,  
	STRSJOBID INT NOT NULL,
		CONSTRAINT PK_TAB_STRSBATCH_STRSBATCHID
		PRIMARY KEY CLUSTERED (STRSBATCHID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSBATCH_STRSJOBID
	ON TAB_STRSBATCH (STRSJOBID ASC)
GO

GRANT SELECT ON TAB_STRSBATCH TO StrsSolutionDB
GO

DROP INDEX	IX_TAB_STRSSPOOL_STRSBATCHID ON TAB_STRSSPOOL,
			IX_TAB_STRSSPOOL_STRSTRAILERJOBID ON TAB_STRSSPOOL,
			IX_TAB_STRSSPOOL_STRSSPOOOLJOBID ON TAB_STRSSPOOL
GO

DROP TABLE TAB_STRSSPOOL
GO

CREATE TABLE TAB_STRSSPOOL 
(	STRSSPOOLID VARCHAR(20) NOT NULL,
	SPOOLTYPE VARCHAR(20),  
	CREATEDATETIME DATETIME2,   
	COMPLETEDATETIME DATETIME2,   
	TOTALDOCPROCESSED INT, 
	TRAILERRECEIVED DATETIME2,
	TOTALDOCSENT INT,
	SPOOLTITLE VARCHAR(50),
	STRSBATCHID VARCHAR(20), 
	STRSBATCHDATE VARCHAR(15),
	STRSTRAILERJOBID INT,
	STRSSPOOOLJOBID INT NOT NULL
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSSPOOL_STRSBATCHID
	ON TAB_STRSSPOOL (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSSPOOL_STRSTRAILERJOBID
	ON TAB_STRSSPOOL (STRSTRAILERJOBID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSSPOOL_STRSSPOOOLJOBID
	ON TAB_STRSSPOOL (STRSSPOOOLJOBID ASC)
GO

GRANT SELECT ON TAB_STRSSPOOL TO StrsSolutionDB
GO

DROP INDEX	IX_TAB_STRSPOSTPROCESSOR_STRSBATCHID ON TAB_STRSPOSTPROCESSOR,
			IX_TAB_STRSPOSTPROCESSOR_STRSJOBID ON TAB_STRSPOSTPROCESSOR
GO

DROP TABLE TAB_STRSPOSTPROCESSOR
GO

CREATE TABLE TAB_STRSPOSTPROCESSOR 
(	STRSPPID VARCHAR(20) NOT NULL,
	PPQTYPE VARCHAR(20), 
	PPQFILENAME VARCHAR(80),	
	CREATEDATETIME DATETIME2,   
	COMPLETEDATETIME DATETIME2,   
	TOTALDOCPROCESSED INT, 
	STRSBATCHID VARCHAR(20), 
	STRSJOBID INT NOT NULL,
		CONSTRAINT PK_TAB_STRSPOSTPROCESSOR_STRSPPID
		PRIMARY KEY CLUSTERED (STRSPPID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTPROCESSOR_STRSBATCHID
	ON TAB_STRSPOSTPROCESSOR (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTPROCESSOR_STRSJOBID
	ON TAB_STRSPOSTPROCESSOR (STRSJOBID ASC)

GRANT SELECT ON TAB_STRSPOSTPROCESSOR TO StrsSolutionDB
GO

DROP INDEX	IX_TAB_STRSAFP_STRSSSORTFILEID ON TAB_STRSAFP,
			IX_TAB_STRSAFP_STRSBATCHID ON TAB_STRSAFP,
			IX_TAB_STRSAFP_STRSJOBID ON TAB_STRSAFP
GO

DROP TABLE TAB_STRSAFP
GO

CREATE TABLE TAB_STRSAFP 
(	STRSAFPID VARCHAR(100) NOT NULL, 
	AFPFILENAME VARCHAR(80),
	SORTCODE VARCHAR(10),
	PLEX VARCHAR(10),	  
	COMPLETEDATETIME DATETIME2,   
	TOTALDOCPROCESSED INT, 
	AFPFILEPATH VARCHAR(150),
	BATCHDATE VARCHAR(8),
	STRSSSORTFILEID VARCHAR(30),
	STRSBATCHID VARCHAR(20), 
	STRSJOBID INT NOT NULL,
	BEGINPSTRAYID INT,
	ENDPSTRAYID INT,
	BEGINPSSEQUENCE INT,
	ENDPSSEQUENCE INT,
		CONSTRAINT PK_TAB_STRSAFP_STRSAFPID
		PRIMARY KEY CLUSTERED (STRSAFPID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSAFP_STRSSSORTFILEID
	ON TAB_STRSAFP (STRSSSORTFILEID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSAFP_STRSBATCHID
	ON TAB_STRSAFP (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSAFP_STRSJOBID
	ON TAB_STRSAFP (STRSJOBID ASC)
GO

GRANT SELECT ON TAB_STRSAFP TO StrsSolutionDB
GO

DROP INDEX	IX_TAB_STRSINSERTS_STRSDOCID ON TAB_STRSINSERTS,
			IX_TAB_STRSINSERTS_BINNUMBER ON TAB_STRSINSERTS
GO

DROP TABLE TAB_STRSINSERTS
GO

CREATE TABLE TAB_STRSINSERTS
(	STRSINSERTID VARCHAR(80) NOT NULL, 
	CREATEDATETIME DATETIME2,
	INSERTDESCRIPTION VARCHAR(80),
	INSERTWEIGHT DECIMAL(5,2),
	BINNUMBER INT,	
	STRSDOCID VARCHAR(50) NOT NULL,  
		CONSTRAINT PK_TAB_STRSINSERTS_STRSINSERTID
		PRIMARY KEY CLUSTERED (STRSINSERTID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSINSERTS_STRSDOCID
	ON TAB_STRSINSERTS (STRSDOCID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSINSERTS_BINNUMBER
	ON TAB_STRSINSERTS (BINNUMBER ASC)
GO

GRANT SELECT ON TAB_STRSINSERTS TO StrsSolutionDB
GO

DROP INDEX	IX_TAB_STRSINV_STRSAFPID ON TAB_STRSINV,
			IX_TAB_STRSINV_STRSSPOOLID ON TAB_STRSINV,
			IX_TAB_STRSINV_STRSBATCHID ON TAB_STRSINV,
			IX_TAB_STRSINV_STRSJOBID ON TAB_STRSINV,
			IX_TAB_STRSINV_CHANNEL ON TAB_STRSINV,
			IX_TAB_STRSINV_DOCUMENTTYPE ON TAB_STRSINV
GO

DROP TABLE TAB_STRSINV
GO
CREATE TABLE TAB_STRSINV
(	STRSDOCID VARCHAR(50) NOT NULL, 
	CREATEDATETIME DATETIME2, 
	DOCUMENTTYPE VARCHAR(20),
	DOCUMENTTITLE VARCHAR(150),
	ACCOUNTNUMBER VARCHAR(15),
	CUSTOMERNAME VARCHAR(50), 
	DOCUMENTDATE VARCHAR(10),
	BILLDUEDATE VARCHAR(10),	
	BILLTYPE VARCHAR(5),
	TOTALAMOUNTDUE VARCHAR(15),
	BILLFROMDATE VARCHAR(10),
	BILLTODATE VARCHAR(10),
	CHANNEL VARCHAR(25), 
	EBILL CHAR(1), 
	RESEND CHAR(1), 
	REPRINT CHAR(1),	
	STRSAFPID VARCHAR(100),
	STRSPPIDARCHIVE VARCHAR(20),
	STRSSPOOLID VARCHAR(20) NOT NULL, 
	STRSBATCHID VARCHAR(20),
	STRSJOBID INT NOT NULL,
	RICEFW VARCHAR(100),
	ADJREVFLAG CHAR(1),
	AUTOPAYFLAG CHAR(1),
	FIRSTFLAG CHAR(1),
	FINALFLAG CHAR(1),
	METERCHANGEFLAG CHAR(1),
	FREDBILLFLAG CHAR(1),
	SREDBILLFLAG CHAR(1),
	BANNERFLAG CHAR(1),
	BANNERCOKEY VARCHAR(40),
	BATCHDATE VARCHAR(15),
	GUID VARCHAR(40),
	LPCPRCNT VARCHAR(20),
	PASTDUEAMOUNT VARCHAR(15),
	REMINDERCODES VARCHAR(40),
	BADADDRESSFLAG CHAR(1),
	DONOTPRINTFLAG CHAR(1),
	EDIFLAG CHAR(1),
	BPNUMBER VARCHAR(12),
	MEMOFLAG CHAR(1),
	HPPFLAG CHAR(1),
	SENIORFLAG CHAR(1),
	LSPFLAG CHAR(1),
	BWBFLAG CHAR(1),
	PAFLAG CHAR(1),
	SPPFLAG CHAR(1),
	OTTFLAG CHAR(1)
	CONSTRAINT PK_TAB_STRSINV_STRSDOCID
		PRIMARY KEY CLUSTERED (STRSDOCID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSINV_STRSAFPID
	ON TAB_STRSINV (STRSAFPID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSINV_STRSSPOOLID
	ON TAB_STRSINV (STRSSPOOLID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSINV_STRSBATCHID
	ON TAB_STRSINV (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSINV_STRSJOBID
	ON TAB_STRSINV (STRSJOBID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSINV_CHANNEL
	ON TAB_STRSINV (CHANNEL ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSINV_DOCUMENTTYPE
	ON TAB_STRSINV (DOCUMENTTYPE ASC)
GO

GRANT SELECT ON TAB_STRSINV TO StrsSolutionDB
GO

DROP INDEX	IX_TAB_STRSCORR_STRSAFPID ON TAB_STRSCORR,
			IX_TAB_STRSCORR_STRSSPOOLID ON TAB_STRSCORR,
			IX_TAB_STRSCORR_STRSBATCHID ON TAB_STRSCORR,
			IX_TAB_STRSCORR_STRSJOBID ON TAB_STRSCORR,
			IX_TAB_STRSCORR_CHANNEL ON TAB_STRSCORR,
			IX_TAB_STRSCORR_DOCUMENTTYPE ON TAB_STRSCORR
GO

DROP TABLE TAB_STRSCORR
GO

CREATE TABLE TAB_STRSCORR
(	STRSDOCID VARCHAR(50) NOT NULL, 
	CREATEDATETIME DATETIME2, 
	DOCUMENTTYPE VARCHAR(20),
	DOCUMENTTITLE VARCHAR(150),
	DOCUMENTCATEGORY VARCHAR(30),
	ACCOUNTNUMBER VARCHAR(15),
	CUSTOMERNAME VARCHAR(50), 
	DOCUMENTDATE VARCHAR(10), 
	CHANNEL VARCHAR(25), 
	RESEND CHAR(1),	
	REPRINT CHAR(1),	
	STRSAFPID VARCHAR(100),
	STRSPPIDARCHIVE VARCHAR(20),
	BATCHDATE VARCHAR(15),
	STRSSPOOLID VARCHAR(20) NOT NULL, 
	STRSBATCHID VARCHAR(20),
	STRSJOBID INT NOT NULL,
	CONSTRAINT PK_TAB_STRSCORR_STRSDOCID
		PRIMARY KEY CLUSTERED (STRSDOCID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCORR_STRSAFPID
	ON TAB_STRSCORR (STRSAFPID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCORR_STRSSPOOLID
	ON TAB_STRSCORR (STRSSPOOLID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCORR_STRSBATCHID
	ON TAB_STRSCORR (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCORR_STRSJOBID
	ON TAB_STRSCORR (STRSJOBID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCORR_CHANNEL
	ON TAB_STRSCORR (CHANNEL ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCORR_DOCUMENTTYPE
	ON TAB_STRSCORR (DOCUMENTTYPE ASC)
GO

GRANT SELECT ON TAB_STRSCORR TO StrsSolutionDB
GO

DROP INDEX	IX_TAB_STRSCOCM_STRSSPOOLID ON TAB_STRSCOCM,
			IX_TAB_STRSCOCM_STRSBATCHID ON TAB_STRSCOCM,
			IX_TAB_STRSCOCM_STRSJOBID ON TAB_STRSCOCM
GO

DROP TABLE TAB_STRSCOCM
GO

CREATE TABLE TAB_STRSCOCM
(	STRSDOCID VARCHAR(50) NOT NULL, 
	CREATEDATETIME DATETIME2, 
	DOCUMENTTYPE VARCHAR(20),
	DOCUMENTCATEGORY VARCHAR(30),
	ACCOUNTNUMBER VARCHAR(15),
	CUSTOMERNAME VARCHAR(50), 
	CUSTOMEREMAIL VARCHAR(200),
	PREMADDRESS VARCHAR(500),
	COCMDATE VARCHAR(10), 
	GUID VARCHAR(40),
	COKEY VARCHAR(40),
	CHANNEL VARCHAR(25), 	
	HTTPRESPONSE VARCHAR(200),
	ARCHIVECOMPLETE CHAR(1),
	STRSSPOOLID VARCHAR(20) NOT NULL, 
	STRSBATCHID VARCHAR(20) NOT NULL,
	STRSJOBID INT NOT NULL,
	CONSTRAINT PK_TAB_STRSCOCM_STRSDOCID
		PRIMARY KEY CLUSTERED (STRSDOCID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCOCM_STRSSPOOLID
	ON TAB_STRSCOCM (STRSSPOOLID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCOCM_STRSBATCHID
	ON TAB_STRSCOCM (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSCOCM_STRSJOBID
	ON TAB_STRSCOCM (STRSJOBID ASC)
GO

GRANT SELECT ON TAB_STRSCOCM TO StrsSolutionDB
GO

DROP INDEX	IX_TAB_STRSEBILL_STRSSPOOLID ON TAB_STRSEBILL,
			IX_TAB_STRSEBILL_STRSBATCHID ON TAB_STRSEBILL,
			IX_TAB_STRSEBILL_STRSJOBID ON TAB_STRSEBILL
GO

DROP TABLE TAB_STRSEBILL
GO

CREATE TABLE TAB_STRSEBILL
(	STRSDOCID VARCHAR(50) NOT NULL, 
	CREATEDATETIME DATETIME2, 
	BILLTYPE VARCHAR(20),
	EMAILADDRESS VARCHAR(250),
	SEGMENT INT,
	HTMLFILE VARCHAR(100), 
	IMAGEFILE VARCHAR(100), 
	CSVFILE	VARCHAR(100), 
	INVOICELLINK VARCHAR(100),
	COKEY VARCHAR(50),
	STRSEBILLEMAILJOBID INT, 
	STRSSPOOLID VARCHAR(20), 
	STRSBATCHID VARCHAR(20),
	STRSJOBID INT,
	CONSTRAINT PK_TAB_STRSEBILL_STRSDOCID
		PRIMARY KEY CLUSTERED (STRSDOCID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSEBILL_STRSSPOOLID
	ON TAB_STRSEBILL (STRSSPOOLID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSEBILL_STRSBATCHID
	ON TAB_STRSEBILL (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSEBILL_STRSJOBID
	ON TAB_STRSEBILL (STRSJOBID ASC)
GO

GRANT SELECT ON TAB_STRSEBILL TO StrsSolutionDB
GO

DROP INDEX	IX_TAB_STRSPOSTALADRS_STRSDOCID ON TAB_STRSPOSTALADRS,
			IX_TAB_STRSPOSTALADRS_STRSCONCATADDRESS ON TAB_STRSPOSTALADRS,
			IX_TAB_STRSPOSTALADRS_SORTCODE ON TAB_STRSPOSTALADRS,
			IX_TAB_STRSPOSTALADRS_STRSENVELOPEID ON TAB_STRSPOSTALADRS,
			IX_TAB_STRSPOSTALADRS_STRSBATCHDATE ON TAB_STRSPOSTALADRS,
			IX_TAB_STRSPOSTALADRS_BPNUMBER ON TAB_STRSPOSTALADRS,
			IX_TAB_STRSPOSTALADRS_STRSSSORTFILEID ON TAB_STRSPOSTALADRS
GO

DROP TABLE TAB_STRSPOSTALADRS
GO

CREATE TABLE TAB_STRSPOSTALADRS 
(	STRSADRSID VARCHAR(20) NOT NULL,  
	MAILTYPE VARCHAR(10), 
	SORTCODE VARCHAR(10),
	DPCUSTOMERNAME VARCHAR(50), 	
	DPATT VARCHAR(50), 
	DPSECDADDR VARCHAR(50),
	DPADDRLINE1 VARCHAR(50), 
	DPADDRLINE2 VARCHAR(50), 
	DPZIP VARCHAR(5),
	DPZIPEXT VARCHAR(10),
	DPCITY VARCHAR(40),
	DPSTATE VARCHAR(5), 
	DPCOUNTRY VARCHAR(20),
	FOREIGNADDRESS CHAR(1),
	COPIES INT,	
	PAGECOUNT INT,
	SHEETCOUNT INT,
	WEIGHT DECIMAL(5,2),
	SCANLINE VARCHAR(60),
	STRSDOCID VARCHAR(50) NOT NULL,
	STRSCONCATADDRESS VARCHAR(500),
	STRSENVELOPEID VARCHAR(50),
	STRSSSORTFILEID VARCHAR(30),
	STRSMULTICOUPONFLAG CHAR(1),
	STRSBATCHDATE VARCHAR(15),
	BPNUMBER VARCHAR(12),
	CONSTRAINT PK_TAB_STRSPOSTALADRS_STRSADRSID 
		PRIMARY KEY CLUSTERED (STRSADRSID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_BPNUMBER 
	ON TAB_STRSPOSTALADRS (BPNUMBER ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_STRSBATCHDATE
	ON TAB_STRSPOSTALADRS (STRSBATCHDATE ASC)
GO
CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_STRSDOCID
	ON TAB_STRSPOSTALADRS (STRSDOCID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_STRSCONCATADDRESS
	ON TAB_STRSPOSTALADRS (STRSCONCATADDRESS ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_SORTCODE
	ON TAB_STRSPOSTALADRS (SORTCODE ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_STRSENVELOPEID
	ON TAB_STRSPOSTALADRS (STRSENVELOPEID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALADRS_STRSSSORTFILEID
	ON TAB_STRSPOSTALADRS (STRSSSORTFILEID ASC)
GO

GRANT SELECT ON TAB_STRSPOSTALADRS TO StrsSolutionDB
GO




DROP INDEX	IX_TAB_STRSPOSTALOPT_STRSSSORTFILEID ON TAB_STRSPOSTALOPT,
			IX_TAB_STRSPOSTALOPT_STRSJOBID ON TAB_STRSPOSTALOPT,
			IX_TAB_STRSPOSTALOPT_STRSBATCHDATE ON TAB_STRSPOSTALOPT,
			IX_TAB_STRSPOSTALOPT_STRSENVELOPEID ON TAB_STRSPOSTALOPT
GO

DROP TABLE TAB_STRSPOSTALOPT
GO

CREATE TABLE TAB_STRSPOSTALOPT 
(	STRSENVELOPEID VARCHAR(50) NOT NULL,  
	MAILTYPE VARCHAR(10),
	DSCUSTOMERNAME VARCHAR(50),
	DSATT VARCHAR(50),
	DSSECDADDR VARCHAR(50),
	DSADDRESSLINE1 VARCHAR(50),
	DSADDRESSLINE2 VARCHAR(50),
	DSZIP INT,
	DSZIPEXT VARCHAR(10),
	DSCITY VARCHAR(40),
	DSSTATE VARCHAR(5),
	DSCOUNTRY VARCHAR(20),	
	DSDPVSTATUS INT,
	DSROUTECODE VARCHAR(5),
	DSMEMOIDN INT,
	DSNCOAFLAG char(1),
	PSZIPMARK char(1),
	PSENDORSELINE VARCHAR(100),
	PSOUTPUTCLASS VARCHAR(50),
	PSIMBBARCODE VARCHAR(50),
	PSTRAYID INT,
	PSPALLETID INT,
	PSSEQUENCE INT,
	PSTRAYSIZE INT,
	STRSSSORTFILEID VARCHAR(30),
 	STRSJOBID INT,
	STRSMULTICOUPONFLAG CHAR(1),
	STRSBATCHDATE VARCHAR(10),
	SORTCODE VARCHAR(10),
	STRSAFPID VARCHAR(100)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALOPT_STRSSSORTFILEID
	ON TAB_STRSPOSTALOPT (STRSSSORTFILEID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALOPT_STRSENVELOPEID
	ON TAB_STRSPOSTALOPT (STRSENVELOPEID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALOPT_STRSJOBID
	ON TAB_STRSPOSTALOPT (STRSJOBID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALOPT_STRSBATCHDATE
	ON TAB_STRSPOSTALOPT (STRSBATCHDATE ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPOSTALOPT_STRSAFPID
	ON TAB_STRSPOSTALOPT (STRSAFPID ASC)
GO

GRANT SELECT ON TAB_STRSPOSTALOPT TO StrsSolutionDB
GO

DROP INDEX	IX_TAB_STRSPRESORTFILE_STRSBATCHID ON TAB_STRSPRESORTFILE,
			IX_TAB_STRSPRESORTFILE_STRSJOBID ON TAB_STRSPRESORTFILE
GO

DROP TABLE TAB_STRSPRESORTFILE
GO

CREATE TABLE TAB_STRSPRESORTFILE 
(	STRSSSORTFILEID VARCHAR(30) NOT NULL, 
	SORTCODE VARCHAR(10),
	FILENAME VARCHAR(80), 
	RECORDCOUNTSENT INT, 
	RECORDCOUNTRETURNED INT, 
	SENTDATETIME DATETIME2,
	RETURNEDDATETIME DATETIME2,
	DOCUPDENDDATETIME DATETIME2,
	PROCESSCOMPLETE INT, 
	STRSBATCHID VARCHAR(20) NOT NULL,
	STRSJOBID INT NOT NULL,
	CONSTRAINT PK_TAB_STRSPRESORTFILE_STRSSSORTFILEID
		PRIMARY KEY CLUSTERED (STRSSSORTFILEID ASC)
)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPRESORTFILE_STRSBATCHID
	ON TAB_STRSPRESORTFILE (STRSBATCHID ASC)
GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSPRESORTFILE_STRSJOBID
	ON TAB_STRSPRESORTFILE (STRSJOBID ASC)

GRANT SELECT ON TAB_STRSPRESORTFILE TO StrsSolutionDB
GO

DROP INDEX	IX_TAB_STRSNOTIFICATIONS_STRSJOBID ON TAB_STRSNOTIFICATIONS
GO

DROP TABLE TAB_STRSNOTIFICATIONS
GO

CREATE TABLE TAB_STRSNOTIFICATIONS
(	STRNOTIFICATIONID VARCHAR(20) NOT NULL,
	CREATEDATETIME DATETIME2,
	NOTIFICATIONTYPE VARCHAR(20), 
	NOTIFICATIONCLASS VARCHAR(10), 
	STRSJOBID INT NOT NULL, 
	BATCHDATE VARCHAR(8),
	PROJECTNAME VARCHAR(40), 
	FUNCTIONCLASS VARCHAR(5), 
	FUNCTIONCNAME VARCHAR(50),
	NOTIFICATION VARCHAR(1000))

GO

CREATE NONCLUSTERED INDEX IX_TAB_STRSNOTIFICATIONS_STRSJOBID
	ON TAB_STRSNOTIFICATIONS (STRSJOBID ASC)
GO

GRANT SELECT ON TAB_STRSNOTIFICATIONS TO StrsSolutionDB
GO