

DROP PROCEDURE SP_DELETE_EXPIRED_RECORDS
GO

-- ================================================
-- Template generated from Template Explorer using:
-- Create Procedure (New Menu).SQL
--
-- Use the Specify Values for Template Parameters
-- command (Ctrl-Shift-M) to fill in the parameter
-- values below.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:          Don Orazulume
-- Modified date:   2017 03 28
-- Description:     DELETE records from StrsSolutionDB where TAB_STRSJOBAUDIT.STRSJOBBEGIN < given date
-- =============================================
CREATE PROCEDURE SP_DELETE_EXPIRED_RECORDS
     -- Add the parameters for the stored procedure here
     @p_DELETEDATE DATETIME2
AS	 
BEGIN
     -- SET NOCOUNT ON added to prevent extra result sets from
     -- interfering with SELECT statements.
     SET NOCOUNT ON
		
		DELETE FROM TAB_STRSINSERTS WHERE STRSDOCID
			IN (SELECT 	STRSDOCID 
				FROM 	TAB_STRSINV i JOIN TAB_STRSJOBAUDIT j ON j.STRSJOBID = i.STRSJOBID
				WHERE 	j.STRSJOBBEGIN < @p_DELETEDATE)
		
		DELETE FROM TAB_STRSINSERTS WHERE STRSDOCID
			IN (SELECT 	STRSDOCID 
				FROM 	TAB_STRSCORR i JOIN TAB_STRSJOBAUDIT j ON j.STRSJOBID = i.STRSJOBID
				WHERE 	j.STRSJOBBEGIN < @p_DELETEDATE)
		
		DELETE FROM TAB_STRSPOSTALADRS WHERE STRSDOCID
			IN (SELECT 	STRSDOCID 
				FROM 	TAB_STRSINV i JOIN TAB_STRSJOBAUDIT j ON j.STRSJOBID = i.STRSJOBID
				WHERE 	j.STRSJOBBEGIN < @p_DELETEDATE)
		
		DELETE FROM TAB_STRSPOSTALADRS WHERE STRSDOCID
			IN (SELECT 	STRSDOCID 
				FROM 	TAB_STRSCORR i JOIN TAB_STRSJOBAUDIT j ON j.STRSJOBID = i.STRSJOBID
				WHERE 	j.STRSJOBBEGIN < @p_DELETEDATE)
		
		DELETE FROM TAB_STRSINV WHERE STRSJOBID 
			IN (SELECT STRSJOBID FROM TAB_STRSJOBAUDIT WHERE STRSJOBBEGIN < @p_DELETEDATE)
			
		DELETE FROM TAB_STRSCORR WHERE STRSJOBID 
			IN (SELECT STRSJOBID FROM TAB_STRSJOBAUDIT WHERE STRSJOBBEGIN < @p_DELETEDATE)
			
		DELETE FROM TAB_STRSCOCM WHERE STRSJOBID 
			IN (SELECT STRSJOBID FROM TAB_STRSJOBAUDIT WHERE STRSJOBBEGIN < @p_DELETEDATE)
			
		DELETE FROM TAB_STRSEBILL WHERE STRSJOBID 
			IN (SELECT STRSJOBID FROM TAB_STRSJOBAUDIT WHERE STRSJOBBEGIN < @p_DELETEDATE)
			
		DELETE FROM TAB_STRSPOSTALOPT WHERE STRSJOBID 
			IN (SELECT STRSJOBID FROM TAB_STRSJOBAUDIT WHERE STRSJOBBEGIN < @p_DELETEDATE)
		
		DELETE FROM TAB_STRSPRESORTFILE WHERE STRSJOBID 
			IN (SELECT STRSJOBID FROM TAB_STRSJOBAUDIT WHERE STRSJOBBEGIN < @p_DELETEDATE)
			
		DELETE FROM TAB_STRSAFP WHERE STRSJOBID 
			IN (SELECT STRSJOBID FROM TAB_STRSJOBAUDIT WHERE STRSJOBBEGIN < @p_DELETEDATE)
			
		DELETE FROM TAB_STRSSPOOL WHERE STRSSPOOOLJOBID 
			IN (SELECT STRSJOBID FROM TAB_STRSJOBAUDIT WHERE STRSJOBBEGIN < @p_DELETEDATE)
			
		DELETE FROM TAB_STRSSPOOL WHERE STRSTRAILERJOBID 
			IN (SELECT STRSJOBID FROM TAB_STRSJOBAUDIT WHERE STRSJOBBEGIN < @p_DELETEDATE)
			
		DELETE FROM TAB_STRSBATCH WHERE STRSJOBID 
			IN (SELECT STRSJOBID FROM TAB_STRSJOBAUDIT WHERE STRSJOBBEGIN < @p_DELETEDATE)
		  
END
GO

GRANT EXECUTE ON SP_DELETE_EXPIRED_RECORDS TO StrsSolutionDB
GO
