select count(*) TAB_STRSINV from TAB_STRSINV
select top 1 * from TAB_STRSINV
select count(*) TAB_STRSCORR from TAB_STRSCORR 
select count (*) TAB_STRSPOSTALADRS from TAB_STRSPOSTALADRS
select top 2 * from TAB_STRSPOSTALADRS
--select count(*) VW_ENVELOPE_DETAIL from VW_ENVELOPE_DETAIL
--select top 2 * from VW_ENVELOPE_DETAIL
select * from TAB_STRSBATCH
select * from TAB_STRSSPOOL
select * from TAB_STRSPRESORTFILE
select sum(RECORDCOUNTSENT) TOT_RECORDCOUNTSENT, sum(RECORDCOUNTRETURNED) TOT_RECORDCOUNTRETURNED from TAB_STRSPRESORTFILE
select count (*) TAB_STRSPOSTALOPT from TAB_STRSPOSTALOPT
select top 2 * from TAB_STRSPOSTALOPT
select datediff(minute, STRSJOBBEGIN, STRSJOBEND) DURATION, * from TAB_STRSJOBAUDIT where STRSINPUTCHANNEL ='in_ppq_afp'
select * from VW_INV_MAIL_REPORT
select * from VW_CORR_MAIL_REPORT